sudo: false
script: /tmp/testrunner/bin/run -c .
before_install:
- curl --silent https://shunit2.googlecode.com/files/shunit2-2.1.6.tgz | tar xz -C
  /tmp/
- git clone https://github.com/heroku/heroku-buildpack-testrunner.git /tmp/testrunner
env:
  global:
  - SHUNIT_HOME="/tmp/shunit2-2.1.6"